name: Node.js Package Lint, Test and Publish

on:
  push:
    branches:
      - "master"

jobs:
  lint-test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install, test, build
        run: |
          npm install
          npm test
          npm build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
